# Default values for hnypots.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: registry.svc.bluescripts.net/ifcfg/web
  tag: latest
  pullPolicy: Always
service:
  name: web
  type: ClusterIP
  externalPort: 80
  internalPort: 5000
ingress:
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - ifcfg.svc.bluescripts.net
resources:
  limits:
#    cpu: 1500m
    memory: 128Mi
  requests:
#    cpu: 300m
    memory: 128Mi
